language: ruby
sudo: required
services:
- docker
before_install:
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee
  -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update
- sudo apt-get install -y dpkg
- sudo apt-get install google-cloud-sdk
- curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.10.5/bin/linux/amd64/kubectl;
  chmod +x ./kubectl; sudo mv ./kubectl /usr/bin/
- sudo apt-get install jq
- echo $GCP_KEY_FILE | base64 -d > ./keyfile
- gcloud auth activate-service-account -q $(jq -r .client_email keyfile) --key-file=./keyfile
  --project  $(jq -r .project_id keyfile)
- rm ./keyfile
install: true
script:
- TESTUSER=vagrant
- TESTGCPMACHINE=openshift4x-test
- pwd
- #if gcloud compute instances describe {$TESTGCPMACHINE} --project "capable-stream-180018" --zone "us-east4-a" | grep status | grep RUNNING ; then echo "Test machine is already running, likely in use. Unable to continue this test run, exiting"; exit; fi
- gcloud compute instances start {$TESTGCPMACHINE} --project "capable-stream-180018" --zone "us-east4-a"
- rm ~/.ssh/google_compute_* || echo "GCP certs were clean"
- gcloud compute --project "capable-stream-180018" scp --zone "us-east4-a" --force-key-file-overwrite --quiet ci/* "{$TESTUSER}@{$TESTGCPMACHINE}:/opt/" # Copy scripts
- gcloud compute --project "capable-stream-180018" ssh --zone "us-east4-a" "{$TESTUSER}@{$TESTGCPMACHINE}" --quiet --command "/opt/shutdownCrc" || echo "crc was already stopped"
- gcloud compute --project "capable-stream-180018" ssh --zone "us-east4-a" "{$TESTUSER}@{$TESTGCPMACHINE}" --quiet --command "/opt/startCrc"
- gcloud compute --project "capable-stream-180018" ssh --zone "us-east4-a" "{$TESTUSER}@{$TESTGCPMACHINE}" --quiet --command "/opt/installBroker"
- gcloud compute --project "capable-stream-180018" ssh --zone "us-east4-a" "{$TESTUSER}@{$TESTGCPMACHINE}" --quiet --command "/opt/testBroker" | tee out.txt
- grep "aurelia" out.txt
- grep "<redundancy-status>Up</redundancy-status>" out.txt
- grep "<oper-status>Up</oper-status>" out.txt
- grep 100000 out.txt
- gcloud compute --project "capable-stream-180018" ssh --zone "us-east4-a" "{$TESTUSER}@{$TESTGCPMACHINE}" --quiet --command "/opt/deleteBroker"
- gcloud compute --project "capable-stream-180018" ssh --zone "us-east4-a" "{$TESTUSER}@{$TESTGCPMACHINE}" --quiet --command "/opt/shutdownCrc"

after_success:
- echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
- echo "SEMP and Messaging tested"
