apiVersion: v1
kind: Template
metadata:
  name: solace-vmr-template
  namespace: prototype
  annotations:
    description: Creates a Solace VMR Pod
    iconClass: icon-phalcon
    tags: messaging
objects:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: '${POD_NAME}'
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
          image: '172.30.3.53:5000/vmr-openshift-demo/solace-app'
          name: vmr
          env:
          - name: USERNAME_${ADMIN_USER}_PASSWORD
            value: '${ADMIN_PASSWORD}'
          - name: USERNAME_${ADMIN_USER}_GLOBALACCESSLEVEL
            value: 'admin'
          - name: SERVICE_SSH_PORT
            value: '22'
          - name:
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          securityContext:
            privileged: true
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 55555
              protocol: TCP
            - containerPort: 22
              protocol: TCP
parameters:
  - name: POD_NAME
    description: The name of the Solace Messaging service to create
    generate: expression
    from: '[A-Z0-9]{8}'
  - name: ADMIN_USER
    description: Username of the admin user
    generate: expression
    from: '[A-Z0-9]{8}'
  - name: ADMIN_PASSWORD
    description: Password of the admin user
    generate: expression
    from: '[A-Z0-9]{8}'