apiVersion: v1
kind: Template
metadata:
  name: solace-vmr-template
  annotations:
    description: Creates a Solace VMR Pod
    iconClass: icon-phalcon
    tags: messaging
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-vmr'
    spec:
      strategy:
        type: Rolling
        rollingParams:
          timeoutSeconds: 1200
          maxSurge: 0
          maxUnavailable: 1
      triggers:
        - type: ConfigChange
      replicas: 1
      selector:
        deploymentconfig: '${APPLICATION_NAME}-vmr'
      template:
        metadata:
          name: '${APPLICATION_NAME}-vmr'
          labels:
            name: '${APPLICATION_NAME}-vmr'
            deploymentconfig: '${APPLICATION_NAME}-vmr'
        spec:
          volumes:
          - name: dshm
            emptyDir:
              medium: Memory
          containers:
            - name: "solace-vmr"
              env:
              - name: USERNAME_${ADMIN_USER}_PASSWORD
                value: '${ADMIN_PASSWORD}'
              - name: USERNAME_${ADMIN_USER}_GLOBALACCESSLEVEL
                value: 'admin'
              - name: SERVICE_SSH_PORT
                value: '22'
              - name: ALWAYS_DIE_ON_FAILURE
                value: '0'
              - name: ROUTERNAME
                value: '${ROUTER_NAME}'
              - name: NODETYPE
                value: '${NODE_TYPE}'
              image: "${VMR_IMAGE}"
              volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              securityContext:
                privileged: true
              ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 943
                protocol: TCP
              - containerPort: 55555
                protocol: TCP
              - containerPort: 55003
                protocol: TCP
              - containerPort: 55556
                protocol: TCP
              - containerPort: 55443
                protocol: TCP
              - containerPort: 80
                protocol: TCP
              - containerPort: 443
                protocol: TCP
              - containerPort: 1883
                protocol: TCP
              - containerPort: 8883
                protocol: TCP
              - containerPort: 8000
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
              - containerPort: 9000
                protocol: TCP
              - containerPort: 9443
                protocol: TCP
              - containerPort: 22
                protocol: TCP
              readinessProbe:
                initialDelaySeconds: 30
                periodSeconds: 5
                tcpSocket:
                  port: 55555
              livenessProbe:
                timeoutSeconds: 6
                initialDelaySeconds: 300
                periodSeconds: 60
                tcpSocket:
                  port: 55555
  - kind: Service
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-vmr'
      annotations:
        description: 'Exposes the VMR services'
    spec:
      ports:
      - name: 'semp'
        port: 8080
        targetPort: 8080
      - name: 'semp-secure'
        port: 943
        targetPort: 943
      - name: 'smf'
        port: 55555
        targetPort: 55555
      - name: 'smf-zip'
        port: 55003
        targetPort: 55003
      - name: 'smf-routing'
        port: 55556
        targetPort: 55556
      - name: 'smf-secure'
        port: 55443
        targetPort: 55443
      - name: 'smf-http'
        port: 80
        targetPort: 80
      - name: 'smf-https'
        port: 443
        targetPort: 443
      - name: 'mqtt'
        port: 1883
        targetPort: 1883
      - name: 'mqtt-secure'
        port: 8883
        targetPort: 8883
      - name: 'mqtt-http'
        port: 8000
        targetPort: 8000
      - name: 'mqtt-https'
        port: 8443
        targetPort: 8443
      - name: 'rest'
        port: 9000
        targetPort: 9000
      - name: 'rest-secure'
        port: 9443
        targetPort: 9443
      - name: 'ssh'
        port: 22
        targetPort: 22
      selector:
        deploymentconfig: '${APPLICATION_NAME}-vmr'
      type: ClusterIP
      sessionAffinity: None
  - kind: Route
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-semp'
    spec:
      host: 'semp.${APPLICATION_SUBDOMAIN}'
      to:
        kind: Service
        name: '${APPLICATION_NAME}-vmr'
      port:
        targetPort: semp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow
      wildcardPolicy: None
  - kind: Route
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-smf-http'
    spec:
      host: 'smf.${APPLICATION_SUBDOMAIN}'
      to:
        kind: Service
        name: '${APPLICATION_NAME}-vmr'
      port:
        targetPort: smf-http
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow
      wildcardPolicy: None
  - kind: Route
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-mqtt-http'
    spec:
      host: 'mqtt.${APPLICATION_SUBDOMAIN}'
      to:
        kind: Service
        name: '${APPLICATION_NAME}-vmr'
      port:
        targetPort: mqtt-http
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow
      wildcardPolicy: None
  - kind: Route
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-rest'
    spec:
      host: 'rest.${APPLICATION_SUBDOMAIN}'
      to:
        kind: Service
        name: '${APPLICATION_NAME}-vmr'
      port:
        targetPort: rest
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow
      wildcardPolicy: None
parameters:
  - name: APPLICATION_NAME
    displayName: Application Name
    description: The suffix to use for object names
    generate: expression
    from: '[A-Z0-9]{8}'
    value: example
    required: true
  - name: APPLICATION_SUBDOMAIN
    displayName: Application Subdomain
    description: The subdomain the template uses for its routes hostnames.
    value: app.openshift.exampledomain.com
  - name: VMR_IMAGE
    displayName: VMR Image
    description: Fully qualified VMR image name.
    value: 172.30.3.53:5000/vmr-openshift-demo/solace-app
  - name: ROUTER_NAME
    displayName: Router Name
    description: The name of the router to instantiate.
    value: vmr1
  - name: NODE_TYPE
    displayName: VMR Node Type
    description: The role of this VMR Node.  Can be either message_routing or monitoring.  Monitoring is used only in HA group.
    value: message_routing
  - name: ADMIN_USER
    description: Username of the admin user
    generate: expression
    from: '[A-Z0-9]{8}'
    value: admin
  - name: ADMIN_PASSWORD
    description: Password of the admin user
    generate: expression
    from: '[A-Z0-9]{8}'
    value: admin