kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-solace-in-unprivileged-container
allowPrivilegedContainer: false
allowedCapabilities: 
 - IPC_LOCK
 - SYS_NICE
 - SETPCAP
 - MKNOD
 - AUDIT_WRITE
 - CHOWN
 - NET_RAW
 - DAC_OVERRIDE
 - FOWNER
 - FSETID
 - KILL
 - SETGID
 - SETUID
 - NET_BIND_SERVICE
 - SYS_CHROOT
 - SETFCAP
allowHostIPC: true
defaultCapabilities:
 - IPC_LOCK
 - SYS_NICE
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: MustRunAs
  ranges:
  - min: 501
    max: 501
supplementalGroups:
  type: RunAsAny
users:
- my-admin-user
groups:
- my-admin-group

